-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TYPE order_payment_type AS ENUM ('BOOKING_PAYMENT', 'INITIAL_PAYMENT', 'CLOSING_PAYMENT', 'FIXED_PAYMENT');
